#
TARGET	= $(COMP_TARGET)
APOBJS	= $(TARGET).o

TMAXLIBD= $(TMAXDIR)/lib

TMAXLIBS= -lclithr -lpthread 
CFLAGS	= -O -I$(TMAXDIR) -D_TMAX_MTLIB

#
.SUFFIXES : .c

.c.o: 
	$(CC) $(CFLAGS) -c $<

#
# client compile
#

$(TARGET): $(APOBJS)
	$(CC) $(CFLAGS) -L$(TMAXLIBD) -o $(TARGET) $(APOBJS) $(TMAXLIBS) 

#
clean:
	-rm -f *.o core $(TARGET)
